background #0f0f1a
foreground #ededfe

font_size 12

background_opacity 0.60
background_blur 1

font_family IoskeleyMonoTerm Nerd Font SemiBold

modify_font cell_width 85%
modify_font cell_height 108%

window_padding_width 8

resize_in_steps yes

confirm_os_window_close 0

cursor_blink_interval 0.5


cursor #ededfe
cursor_text_color #0f0f1a

selection_foreground #ededff
selection_background #202036

color0 #d0d0d0
color1 #ff0063
color2 #00f992
color3 #ffe900
color4 #00a4ff
color5 #ff57fd
color6 #00ffed
color7 #ededff

color8 #d0d0d0
color9 #d0d0d0
color10 #00fcb9
color11 #ffff68
color12 #3ea0ff
color13 #ff93ff
color14 #38ffff
color15 #f8f8ff
