# =============================================================================
# Window & Behaviour configuration
# =============================================================================

window_padding_width     8

background_opacity       1
background_blur          1

resize_in_steps          yes

confirm_os_window_close  0

cursor_blink_interval    0.5
