set -g status-interval 3

set -g status on
set -g status-position top
set -g status-justify left

set -g status-style "bg=#0f0f1a,fg=#ededfe"

set -g status-left         "#[bg=#00ffed,fg=#0f0f1a,bold] #S #[bg=#0f0f1a,fg=#00ffed,nobold]"
set -g status-left-length  30

set -g status-right-length 50
set -g status-right "#[fg=#5c6675]#[bg=#5c6675,fg=#00ffed] %H:%M #[bg=#5c6675,fg=#ededfe]│#[fg=#ededfe] %d/%m/%Y #[bg=#5c6675,fg=#0f0f1a]"

set -g window-status-format         "#[bg=#0f0f1a,fg=#5c6675]▎#[fg=#708090] #I #[fg=#8888a0]#{=10:window_name}  "
set -g window-status-style          "bg=#0f0f1a"
set -g window-status-separator      ""

set -g window-status-current-format "#[bg=#1a1a2e,fg=#00ffed]▎#[fg=#00ffed] #I #[fg=#ffffff]#{=10:window_name}  "
set -g window-status-current-style  "bg=#1a1a2e"

set -g window-status-activity-style "bg=#0f0f1a,fg=#ffe900"
set -g window-status-bell-style     "bg=#0f0f1a,fg=#ff0063,bold"

set -g pane-border-style        "fg=#5c6675"
set -g pane-active-border-style "fg=#00a4ff"

set -g message-style        "bg=#5c6675,fg=#00ffed,bold"
set -g message-command-style "bg=#5c6675,fg=#ff57fd,bold"

set -g mode-style "bg=#5c6675,fg=#ffe900"

set -g display-panes-colour        "#5c6675"
set -g display-panes-active-colour "#00a4ff"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
