# Override system brightness bindings with SwayOSD
# Replaces /usr/share/sway/config.d/60-bindings-brightness.conf

# Brightness up
bindsym --locked XF86MonBrightnessUp exec swayosd-client --brightness raise
# Brightness down
bindsym --locked XF86MonBrightnessDown exec swayosd-client --brightness lower
