-- bootstrap lazy.nvim, LazyVim and your plugins
-- vim.opt.number = true
-- vim.opt.relativenumber = true
--
-- vim.opt.splitbelow = true
-- vim.opt.splitright = true
--
-- vim.opt.wrap = false
--
-- vim.opt.expandtab = true
-- vim.opt.tabstop = 2
-- vim.opt.shiftwidth = 2
--
-- vim.opt.clipboard = "unnamedplus"
--
-- vim.opt.ignorecase = true
-- vim.opt.inccommand = "split"
-- vim.opt.termguicolors = true
-- vim.opt.scrolloff = 100
--
require("config.lazy")
