HISTFILE=$ZDOTDIR/zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt autocd correct interactivecomments magicequalsubst notify numericglobsort promptsubst
setopt appendhistory sharehistory hist_ignore_space hist_ignore_all_dups hist_save_no_dups
setopt hist_expire_dups_first hist_find_no_dups
