[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
#command = "agreety --cmd /bin/sh"

#command = "tuigreet --time --remember --cmd hyprland"
#command = "tuigreet --cmd 'uwsm start hyprland' --time --remember --remember-session"
#command = "tuigreet --time --remember --cmd 'env -u  WAYLAND_DISPLAY -u DISPLAY uwsm start hyprland'"
#command = "tuigreet --time --remember --cmd 'systemd-run --user --scope --unit=hyprland uwsm start hyprland'"

command = "tuigreet --time --remember --remember-session --sessions /usr/share/wayland-sessions --asterisks --greeting 'Fedora Hyprland' --theme 'border=white;text=white;prompt=white;time=white;action=white;button=white;container=black'"

user = "greetd"
