# ── Resurrect / Continuum ────────────────────────────────────
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'

# ── Terminal ─────────────────────────────────────────────────
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -sa terminal-features ",*:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58:2::%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%d m'
set -g allow-passthrough on

# ── General ──────────────────────────────────────────────────
set -g mouse on
set -g history-limit 50000
set -g focus-events on
set -s escape-time 0
set -g display-time 1500

# ── Window / Pane ────────────────────────────────────────────
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'
